---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3371476492-Xq1QJSSlNdkMxU6mQmqEexOOUmG9OKXQGwNjbQR
:access_token_secret: 54uGBcpnAtpkQXjwj6R4EfvqocpwqV2XbZz7gcaIPmneE
